export {
  BranchIsolationError,
  assertCurrentBranch,
  assertWorkingTreeClean,
  branchExists,
  buildBranchName,
  describeDirtyWorkingTree,
  ensureFeatureBranch,
  getCurrentBranch,
  isBranchIsolationError,
  isGitRepo,
  projectUsesSharedBranchIsolation,
  slugifyTitle,
  workingTreeClean,
  type EnsureFeatureBranchInput,
  type EnsureFeatureBranchResult,
} from "@aif/shared";
